dataset:
  zarr_path: "/home/emarkley/Workspace/PYTHON/EncodingInformation/color_filter_array/path_to_zarr_dataset"
  mean_photons: 1000
  model_path: '/home/emarkley/Workspace/PYTHON/EncodingInformation/color_filter_array/models/ideal_1000_photons_slow_mask_high_gamma/step_0040000.eqx'
  patch_size: 24
  train_fraction: 0.95
  batch_size: 128

training:
  epochs: 200
  N_models: 40
  num_bootstrap_samples: 100

seeds:
  data_seed: 0

output:
  results_dir: "/home/emarkley/Workspace/PYTHON/EncodingInformation/color_filter_array/mi_results"
  save_name: 'ideal_1000_photons_slow_mask_high_gamma.npz'
