config_file_version: '2.4'
data:
  batch: 1
  channels:
  - DPC_Right
  data_dir: /home/hpinkard_waller/data/
  dataset_name: BSCCM
  shuffle_seed: 1661608293
  synthetic_noise:
    edge_crop: 24
    median_filter: true
    photons_per_pixel: 100
    seed: 1475392113
  use_two_spectrum_unmixing: true
hyperparameters:
  all_marker_training: true
  arch: DN121
  batch_size: 24
  change_input_channels: true
  density_output: true
  learning_rate: 5.0e-05
  max_epochs: 50000
  mixture_type: gaussian
  num_examples_for_normalization: 500
  num_mixture_components: 19
  optimizer: ADAM
  overshoot_epochs: 20
  seed: 1395668066
  single_marker_early_stopping: false
  single_marker_training: false
  steps_per_epoch: 4000
  test_fraction: 0.05
  validation_fraction: 0.05
metadata:
  experiment_name: Synthetic_Noise_v2
  replicate: 0
options:
  hog_memory: false
  immortal: false
  resume_training: false
saving_dir: /home/hpinkard_waller/models/Synthetic_Noise_v2/
train_script_path: /home/hpinkard_waller/GitRepos/EncodingInformation/led_array/phenotyping_experiments/train_model.py
training:
  attempt_number: 7
  elapsed: 3218.6639642715454
  start_date: '2023-11-02'
  tensorboard_dir: /home/hpinkard_waller/models/Synthetic_Noise_v2/Synthetic_Noise_v2_DPC_Right_100_photons_replicate_0/tensorboard/
