name: Build and Publish to PyPI using Flit

on:
  push:
    paths:
      - 'src/encoding_information/_version.py'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Install package dependencies
      run: |
        pip install -e .
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Debug information
      run: |
        pwd
        ls -R
        echo $PYTHONPATH
        pip list
    - name: Build package
      run: flit build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1